# Generated by Django 4.2.4 on 2023-09-04 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Имя заявителя', max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия заявителя', max_length=100, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Отчество заявителя', max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона', max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Почта', max_length=254, null=True, verbose_name='Почта')),
                ('org', models.CharField(blank=True, help_text='Организация', max_length=200, null=True, verbose_name='Организация')),
                ('id_user_tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИД телеграмм пользователя')),
                ('black_list', models.BooleanField(default=False, help_text='ЧС', verbose_name='ЧС')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Systems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название системы', max_length=300, verbose_name='Название системы')),
                ('description', models.TextField(blank=True, help_text='Описание системы', null=True, verbose_name='Описание системы')),
            ],
            options={
                'verbose_name': 'Система',
                'verbose_name_plural': 'Системы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя персоны', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия персоны', max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Отчество персоны', max_length=100, null=True, verbose_name='Отчество')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_completion', models.DateTimeField(auto_now=True, null=True)),
                ('id_appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicants', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Other_applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текст заявки')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('date_completion', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('id_appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicants', verbose_name='Заявитель')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.systems', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Название организации', max_length=300, null=True, verbose_name='Имя')),
                ('inn', models.CharField(max_length=10, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_completion', models.DateTimeField(auto_now=True, null=True)),
                ('id_appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicants', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя персоны', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия персоны', max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Отчество персоны', max_length=100, null=True, verbose_name='Отчество')),
                ('status', models.BooleanField(default=False, verbose_name='Статус заявки')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('date_completion', models.DateTimeField(auto_now=True, null=True)),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН организации')),
                ('post', models.CharField(help_text='Должность', max_length=100, verbose_name='Должность')),
                ('id_appl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicants', verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['date_created'],
            },
        ),
    ]
