# Generated by Django 4.2.4 on 2023-09-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typical_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('text', models.TextField(null=True, verbose_name='Текст ответа')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.systems', verbose_name='Система')),
            ],
        ),
    ]
